POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "author": "anonymous",
    "title": "Test123",
    "url": "absent",
    "likes": 69420,
    "user": "5fba53d82351ba16a8db5cff"
}