POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFhYWEiLCJpZCI6IjVmYmJkMGZjMWZiNTgwMWMxMGY2M2Y2OSIsImlhdCI6MTYwNjE1MDc5Nn0.qW3rTESQafCAQaHnsgFzwqhgixxPFImgt11szH3zpwo
    
{
    "author": "some guy",
    "title": "Last Post, honestly",
    "url": "absent",
    "likes": 69420,
    "user": "5fba53d82351ba16a8db5cff"
}